// js/data.js
const STEPS = [
  {
    id: 'ears',
    title: 'Choose Your Ears',
    subtitle: 'All ears are hand-picked from the finest ear farms.',
  },
  {
    id: 'tail',
    title: 'Choose Your Tail',
    subtitle: 'Tails sold separately. Wagging not included (it just happens).',
  },
  {
    id: 'eyes',
    title: 'Choose Your Eyes',
    subtitle: 'Eyes are the windows to a very good soul.',
  },
  {
    id: 'toofs',
    title: 'Choose Your Toofs',
    subtitle: 'Dental grade. Vet approved. Kibble-tested.',
  },
  {
    id: 'legs',
    title: 'Choose Your Fur Stick',
    subtitle: 'The leg you know. The stick you love.',
  },
  {
    id: 'coat',
    title: 'Choose Your Coat',
    subtitle: 'Premium fur. Zero synthetic fibers. 100% floof.',
  },
];

const PRODUCTS = [
  // EARS
  {
    id: 'ears-floppy',
    category: 'ears',
    name: 'Premium Floppy Ears',
    price: 14.99,
    description: 'Gravity-assisted. Maximum boing factor certified.',
    svgLayer: 'ears-floppy',
    emoji: '👂',
  },
  {
    id: 'ears-radar',
    category: 'ears',
    name: 'Radar Ears',
    price: 24.99,
    description: 'Can hear a treat bag opening from 3 miles away.',
    svgLayer: 'ears-radar',
    emoji: '📡',
  },
  {
    id: 'ears-satellite',
    category: 'ears',
    name: 'Satellite Dish Ears',
    price: 89.99,
    description: 'Picks up WiFi, squirrel frequencies, and vibes.',
    svgLayer: 'ears-satellite',
    emoji: '🛸',
  },

  // TAIL
  {
    id: 'tail-bushy',
    category: 'tail',
    name: 'Bushy Tail (Deluxe)',
    price: 22.99,
    description: 'Volume that rivals a golden hour sunset.',
    svgLayer: 'tail-bushy',
    emoji: '🦊',
  },
  {
    id: 'tail-stub',
    category: 'tail',
    name: 'Tiny Stub Tail',
    price: 9.99,
    description: 'Less tail, same love. Compact yet extremely enthusiastic.',
    svgLayer: 'tail-stub',
    emoji: '🤏',
  },
  {
    id: 'tail-wag',
    category: 'tail',
    name: 'Full Wag Tail™',
    price: 34.99,
    description: 'Patent-pending perpetual wag technology. No off switch.',
    svgLayer: 'tail-wag',
    emoji: '〰️',
  },

  // EYES
  {
    id: 'eyes-human',
    category: 'eyes',
    name: 'Human Eyes',
    price: 299.99,
    description: 'Unsettling. Wise. Knowing. You will make eye contact and feel understood.',
    svgLayer: 'eyes-human',
    emoji: '👁️',
  },
  {
    id: 'eyes-puppy',
    category: 'eyes',
    name: 'Classic Puppy Eyes',
    price: 18.99,
    description: 'Irresistible. Weaponized cuteness. Use responsibly.',
    svgLayer: 'eyes-puppy',
    emoji: '🥺',
  },
  {
    id: 'eyes-anime',
    category: 'eyes',
    name: 'Anime Sparkle Eyes',
    price: 49.99,
    description: 'Catch the light. Catch feelings. Catch everything.',
    svgLayer: 'eyes-anime',
    emoji: '✨',
  },

  // TOOFS
  {
    id: 'toofs-buck',
    category: 'toofs',
    name: 'Buck Toofs',
    price: 12.99,
    description: 'Two front teeth, front and center. Charming and goofy in equal measure.',
    svgLayer: 'toofs-buck',
    emoji: '🦷',
  },
  {
    id: 'toofs-none',
    category: 'toofs',
    name: 'Smooth (No Toofs)',
    price: 0.00,
    description: 'A toof-free experience. Gummy. Serene. Gumsmooths only.',
    svgLayer: 'toofs-none',
    emoji: '😶',
  },
  {
    id: 'toofs-vampire',
    category: 'toofs',
    name: 'Vampire Toofs',
    price: 666.00,
    description: 'Fangs of distinction. Still a very good boy though.',
    svgLayer: 'toofs-vampire',
    emoji: '🧛',
  },

  // LEGS
  {
    id: 'legs-outstretched',
    category: 'legs',
    name: 'Outstretched Fur Stick',
    price: 19.99,
    description: 'The classic. One leg. Fully extended. Maximum reach.',
    svgLayer: 'legs-outstretched',
    emoji: '🦴',
  },
  {
    id: 'legs-zoomies',
    category: 'legs',
    name: 'Zoomies Mode',
    price: 44.99,
    description: 'All four legs mid-stride. Perpetually at top speed. No brakes.',
    svgLayer: 'legs-zoomies',
    emoji: '💨',
  },
  {
    id: 'legs-derp',
    category: 'legs',
    name: 'Derp Tuck',
    price: 11.99,
    description: 'Legs folded under. Maximum loaf. Zero aerodynamics.',
    svgLayer: 'legs-derp',
    emoji: '🍞',
  },

  // COAT
  {
    id: 'coat-golden',
    category: 'coat',
    name: 'Golden Doodle',
    price: 79.99,
    description: 'Sun-kissed. Bouncy. Radiates pure warmth and chaos.',
    svgLayer: 'coat-golden',
    furColor: '#D4A028',
    emoji: '☀️',
  },
  {
    id: 'coat-spotty',
    category: 'coat',
    name: 'Spotty Boi',
    price: 59.99,
    description: 'Classic spots. Each one unique. Each one perfect.',
    svgLayer: 'coat-spotty',
    furColor: '#8B4513',
    emoji: '🐄',
  },
  {
    id: 'coat-midnight',
    category: 'coat',
    name: 'Midnight Floof',
    price: 89.99,
    description: 'All black. Mysterious. Absorbs sunlight and compliments.',
    svgLayer: 'coat-midnight',
    furColor: '#1A1A2E',
    emoji: '🌙',
  },
  {
    id: 'coat-silver',
    category: 'coat',
    name: 'Silver Fox',
    price: 99.99,
    description: 'Distinguished. Elegant. Has definitely seen some things.',
    svgLayer: 'coat-silver',
    furColor: '#C0C0C0',
    emoji: '🪙',
  },
];
